version: '3.7'

services:

  app:
    build: .
    tty: true
    stdin_open: true
    container_name: curso
    image: curso
    volumes:
      - ./:/app
    ports:
      - "80:3000"
    networks:
      - networkapp

  postgres:
    container_name: postgres_container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      PGDATA: /var/lib/postgresql/data
    volumes:
      - volumepostgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge
  networkapp:
    driver: bridge

volumes:
  volumepostgres:
